### ISSUE TITLE
Different font in inline math vs $$ math

### ISSUE THREAD

**Issue by cpraveen** [jupyter-book/mystmd#1681] opened 2024-11-27 09:47 UTC
See an example here

https://cpraveen.github.io/numa/intro

See Eq. (17) and notice the alpha, which looks fine. Then immediately on the next line, there is another alpha.

**with $\alpha$ as small as possible**

The inline alpha is rendered with a different font, which almost looks like an "a".

How can I get same font in both $ mode as in $$ mode ?

**Comment by agoose77** [comment] 2024-11-27 14:26
Closing this as a duplicate of https://github.com/jupyter-book/mystmd/issues/1604 

:)

**Closed by agoose77** 2024-11-27 14:26 UTC

**Comment by rowanc1** [comment] 2024-11-27 14:36
Updated a comment in the other post. We can remove the math simplification changes. I will aim to do this today.
