### ISSUE TITLE
Code cells remain in dark mode while page is in light mode

### ISSUE THREAD

**Issue by alimanfoo** [jupyter-book/mystmd#1577] opened 2024-10-11 10:13 UTC
## Description

Hi there :wave: I have created a simple website using the article theme. I am finding that sometimes the code cells remain in dark mode even though the site is switched to light mode. E.g.:

![Image](https://github.com/user-attachments/assets/623c2cef-38ed-414e-9c96-7eca26afeab2)

## Additional notes

Using myst v1.3.12.

Here is the [source code](https://github.com/alimanfoo/anjl/tree/main/docs) and [published site](https://alimanfoo.github.io/anjl/).

**Comment by agoose77** [comment] 2024-10-12 09:10
Duplicate of jupyter-book/myst-theme#473 :)

**Closed by agoose77** 2024-10-12 09:10 UTC
Labels: bug
